version: '3.4'

services:

# Side services

  rabbitmq:
    image: "rabbitmq:3-management-alpine"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - phonebook
  
  mongodb:
    image: mongo
    ports:
      - 27018:27017
    networks:
      - phonebook 

# Manager vs Dapr

  manager:
    image: ${DOCKER_REGISTRY-}manager
    build:
      context: .
      dockerfile: Manager/Dockerfile    
    depends_on:
      - rabbitmq
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - phonebook

   
  manager-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
        "-app-port", "80",
        "-app-id", "manager",
        "-app-protocol", "http",
        "-dapr-http-port", "3500",
        "-components-path", "./dapr/components",
        "-config", "./dapr/config.yaml"
        ]
    volumes:
      - "./dapr/:/dapr"
    depends_on:
      - manager
    network_mode: "service:manager"

# Accessor vs Dapr

  accessor:
    image: ${DOCKER_REGISTRY-}accessor
    build:
      context: .
      dockerfile: Accessor/Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - phonebook

  accessor-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
        "-app-port", "80",
        "-app-id", "accessor",
        "-app-protocol", "http",
        "-dapr-http-port", "3500",
        "-components-path", "./dapr/components",
        "-config", "./dapr/config.yaml"
        ]
    volumes:
      - "./dapr/:/dapr"
    depends_on:
      - accessor
    network_mode: "service:accessor"


networks:
    phonebook:

